// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import Footer from "./components/Footer";
// import UserProvider from "@/context/userProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <UserProvider>
//        <Navbar/>
       
//        <div className="h-screen w-full bg-pink-500 overflow-auto p-1" >
//         {children}
//         </div>
//         </UserProvider>
//        <Footer/>
//       </body>
//     </html>
//   );
// }


// app/layout.jsx
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import UserProvider from "@/context/userProvider";
import "./globals.css"; // Your global styles

export const metadata = {
  title: "Task Manager",
  description: "Manage your tasks efficiently with Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Navbar />
          <div className="min-h-[calc(100vh-80px)] bg-gray-900 text-white"> {/* Adjust height based on Navbar/Footer heights */}
            {children}
          </div>
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}